
package UI.admin;

import UI.ZLoginAll;
import UI.admin.adminPanel.ADashboard;
import UI.admin.adminPanel.AManageCourse;
import UI.admin.adminPanel.AManageEnrollment;
import UI.admin.adminPanel.AManageGraduation;
import UI.admin.adminPanel.AManageLecturer;
import UI.admin.adminPanel.AManageProdi;
import UI.admin.adminPanel.AManageFakultas;
import UI.admin.adminPanel.AManageStudents;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import Session.UserSession;

public class AFrame extends javax.swing.JFrame {

    private CardLayout cardLayout;

    private ADashboard dashboardPanel;
    private AManageCourse manageCoursePanel;
    private AManageEnrollment manageEnrollmentPanel;
    private AManageGraduation manageGraduationPanel;
    private AManageLecturer manageLecturerPanel;
    private AManageProdi manageProdiPanel;
    private AManageFakultas manageFakultasPanel;
    private AManageStudents manageStudentsPanel;


    public AFrame() {
        if (!UserSession.isAdmin()) {
            JOptionPane.showMessageDialog(this,
                "Akses ditolak!",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            dispose();
            return;
        }
        
        initComponents();
        initCard();
    }
    
    private void initCard() {
        cardLayout = new CardLayout();
        jPanel1.setLayout(cardLayout);

        dashboardPanel        = new ADashboard();
        manageCoursePanel     = new AManageCourse();
        manageEnrollmentPanel = new AManageEnrollment();
        manageGraduationPanel = new AManageGraduation();
        manageLecturerPanel   = new AManageLecturer();
        manageProdiPanel      = new AManageProdi();
        manageFakultasPanel   = new AManageFakultas();
        manageStudentsPanel   = new AManageStudents();

        jPanel1.add(dashboardPanel,        "DASHBOARD");
        jPanel1.add(manageCoursePanel,     "COURSE");
        jPanel1.add(manageEnrollmentPanel, "ENROLLMENT");
        jPanel1.add(manageGraduationPanel, "GRADUATION");
        jPanel1.add(manageLecturerPanel,   "LECTURER");
        jPanel1.add(manageProdiPanel,      "PRODI");
        jPanel1.add(manageFakultasPanel,   "FAKULTAS");
        jPanel1.add(manageStudentsPanel,   "STUDENTS");

        cardLayout.show(jPanel1, "DASHBOARD");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Dashboard = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        Fakultas = new javax.swing.JMenuItem();
        Prodi = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        Enrollment = new javax.swing.JMenuItem();
        Course = new javax.swing.JMenuItem();
        Graduation = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        Mahasiswa = new javax.swing.JMenuItem();
        Dosen = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        Dashboard.setText("Dashboard");
        Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardMouseClicked(evt);
            }
        });
        jMenuBar1.add(Dashboard);

        jMenu2.setText("Kampus");

        Fakultas.setText("Fakultas");
        Fakultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FakultasMouseClicked(evt);
            }
        });
        Fakultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FakultasActionPerformed(evt);
            }
        });
        jMenu2.add(Fakultas);

        Prodi.setText("Prodi");
        Prodi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProdiMouseClicked(evt);
            }
        });
        Prodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdiActionPerformed(evt);
            }
        });
        jMenu2.add(Prodi);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Studi");

        Enrollment.setText("Enrollment");
        Enrollment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnrollmentMouseClicked(evt);
            }
        });
        Enrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrollmentActionPerformed(evt);
            }
        });
        jMenu5.add(Enrollment);

        Course.setText("Course");
        Course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseActionPerformed(evt);
            }
        });
        jMenu5.add(Course);

        jMenuBar1.add(jMenu5);

        Graduation.setText("Graduation");
        Graduation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GraduationMouseClicked(evt);
            }
        });
        jMenuBar1.add(Graduation);

        jMenu7.setText("User");

        Mahasiswa.setText("Mahasiswa");
        Mahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MahasiswaMouseClicked(evt);
            }
        });
        Mahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MahasiswaActionPerformed(evt);
            }
        });
        jMenu7.add(Mahasiswa);

        Dosen.setText("Dosen");
        Dosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DosenMouseClicked(evt);
            }
        });
        Dosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DosenActionPerformed(evt);
            }
        });
        jMenu7.add(Dosen);

        jMenuBar1.add(jMenu7);

        jMenu4.setText("Logout");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MahasiswaActionPerformed
        cardLayout.show(jPanel1, "STUDENTS");
    }//GEN-LAST:event_MahasiswaActionPerformed

    private void DosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DosenActionPerformed
        cardLayout.show(jPanel1, "LECTURER");
    }//GEN-LAST:event_DosenActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin logout?",
            "Logout",
            JOptionPane.YES_NO_OPTION
        );
        
        if (confirm == JOptionPane.YES_OPTION) {
            new ZLoginAll().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenu4MouseClicked

    private void DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseClicked
        cardLayout.show(jPanel1, "DASHBOARD");
    }//GEN-LAST:event_DashboardMouseClicked

    private void FakultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FakultasMouseClicked
        cardLayout.show(jPanel1, "FAKULTAS");
    }//GEN-LAST:event_FakultasMouseClicked

    private void ProdiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProdiMouseClicked
        cardLayout.show(jPanel1, "PRODI");
    }//GEN-LAST:event_ProdiMouseClicked

    private void EnrollmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnrollmentMouseClicked
        cardLayout.show(jPanel1, "ENROLLMENT");
    }//GEN-LAST:event_EnrollmentMouseClicked

    private void GraduationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GraduationMouseClicked
        cardLayout.show(jPanel1, "GRADUATION");
    }//GEN-LAST:event_GraduationMouseClicked

    private void MahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MahasiswaMouseClicked
        cardLayout.show(jPanel1, "STUDENTS");
    }//GEN-LAST:event_MahasiswaMouseClicked

    private void DosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DosenMouseClicked
        cardLayout.show(jPanel1, "LECTURER");
    }//GEN-LAST:event_DosenMouseClicked

    private void FakultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FakultasActionPerformed
        cardLayout.show(jPanel1, "FAKULTAS");
    }//GEN-LAST:event_FakultasActionPerformed

    private void ProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdiActionPerformed
        cardLayout.show(jPanel1, "PRODI");
    }//GEN-LAST:event_ProdiActionPerformed

    private void EnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrollmentActionPerformed
        cardLayout.show(jPanel1, "ENROLLMENT");
    }//GEN-LAST:event_EnrollmentActionPerformed

    private void CourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseActionPerformed
        cardLayout.show(jPanel1, "COURSE");
    }//GEN-LAST:event_CourseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Course;
    private javax.swing.JMenu Dashboard;
    private javax.swing.JMenuItem Dosen;
    private javax.swing.JMenuItem Enrollment;
    private javax.swing.JMenuItem Fakultas;
    private javax.swing.JMenu Graduation;
    private javax.swing.JMenuItem Mahasiswa;
    private javax.swing.JMenuItem Prodi;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
