/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI.admin.adminPanel;


import Database.koneksiDB;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
        
public class AlinkUser extends javax.swing.JInternalFrame {
    String textKode, textNama, buffNama;
    koneksiDB db = new koneksiDB();
    Connection con;
    DefaultTableModel tm;
    /**
     * Creates new form FormSiswa
     */
 public AlinkUser() {
    initComponents();
    connect(); // Memanggil connect() dan menyimpan hasilnya di con
    refreshTable();
}
    
    private void connect() {
        con = db.connect();
    }
    
    private void refreshTable() {
        tm = new DefaultTableModel(
        null,
        new Object[] {"Id Mapel", "Nama Mapel"}
        );        
        
        tbmapel.setModel(tm);
        tm.getDataVector().removeAllElements();
        
        try {
            PreparedStatement s = con.prepareStatement("SELECT * FROM mapel");
            ResultSet r = s.executeQuery();
            while (r.next()) {
                Object[] data = {
                    r.getString(1),
                    r.getString(2)
                };
                tm.addRow(data);
            }
        }catch(Exception e) {
                    System.out.println("ERROR QUERY TO DATABASE:\n" + e + "\n\n");
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jbox = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Tfkodekelas = new javax.swing.JTextField();
        Tfnamakelas = new javax.swing.JTextField();
        jbox1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Tfkodekelas1 = new javax.swing.JTextField();
        Tfnamakelas1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbmapel = new javax.swing.JTable();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Link Mahasiswa");

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Batal");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jbox.setBackground(new java.awt.Color(255, 204, 0));
        jbox.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Data"));
        jbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jboxMouseClicked(evt);
            }
        });

        jLabel2.setText("Id");

        jLabel3.setText("Nama User");

        Tfkodekelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfkodekelasActionPerformed(evt);
            }
        });

        Tfnamakelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfnamakelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jboxLayout = new javax.swing.GroupLayout(jbox);
        jbox.setLayout(jboxLayout);
        jboxLayout.setHorizontalGroup(
            jboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jboxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tfkodekelas, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(Tfnamakelas))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jboxLayout.setVerticalGroup(
            jboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jboxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Tfkodekelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Tfnamakelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jbox1.setBackground(new java.awt.Color(255, 204, 0));
        jbox1.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Data"));
        jbox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbox1MouseClicked(evt);
            }
        });

        jLabel4.setText("Id");

        jLabel5.setText("Mahasiswa");

        Tfkodekelas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tfkodekelas1ActionPerformed(evt);
            }
        });

        Tfnamakelas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tfnamakelas1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jbox1Layout = new javax.swing.GroupLayout(jbox1);
        jbox1.setLayout(jbox1Layout);
        jbox1Layout.setHorizontalGroup(
            jbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbox1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tfkodekelas1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(Tfnamakelas1))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jbox1Layout.setVerticalGroup(
            jbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbox1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Tfkodekelas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Tfnamakelas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tbmapel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbmapel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbmapelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbmapel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jButton2)
                        .addGap(13, 13, 13)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfkodekelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfkodekelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfkodekelasActionPerformed

    private void TfnamakelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfnamakelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfnamakelasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            PreparedStatement ps = con.prepareStatement("INSERT INTO mapel VALUES (?,?)");
            ps.setString(1, Tfkodekelas.getText());
            ps.setString(2, Tfnamakelas.getText());
            ps.executeUpdate();
            
            refreshTable();
            Tfkodekelas.setText("");
            Tfnamakelas .setText("");
        }catch(Exception e) {
            System.out.println("ERROR QUERY TO DATABASE:\n" + e + "\n\n");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
        PreparedStatement ps = con.prepareStatement("UPDATE mapel SET namamapel = ? WHERE idmapel = ?");
        ps.setString(1, Tfnamakelas.getText());
        ps.setString(2, Tfkodekelas.getText());
        ps.executeUpdate();

            
            refreshTable();
            Tfkodekelas.setText("");
            Tfnamakelas .setText("");
        }catch(Exception e) {
            System.out.println("ERROR QUERY TO DATABASE:\n" + e + "\n\n");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
        PreparedStatement ps = con.prepareStatement("DELETE FROM mapel WHERE idmapel = ?");
        ps.setString(1, Tfkodekelas.getText());
        ps.executeUpdate();

            refreshTable();
            Tfkodekelas.setText("");
            Tfnamakelas .setText("");
        }catch(Exception e) {
            System.out.println("ERROR QUERY TO DATABASE:\n" + e + "\n\n");
        }
        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jboxMouseClicked
        Tfkodekelas.setText(tm.getValueAt(tbmapel.getSelectedRow(), 0).toString());
        Tfnamakelas.setText(tm.getValueAt(tbmapel.getSelectedRow(), 1).toString());  
    }//GEN-LAST:event_jboxMouseClicked

    private void Tfkodekelas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tfkodekelas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tfkodekelas1ActionPerformed

    private void Tfnamakelas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tfnamakelas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tfnamakelas1ActionPerformed

    private void jbox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbox1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbox1MouseClicked

    private void tbmapelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbmapelMouseClicked
        Tfkodekelas.setText(tm.getValueAt(tbmapel.getSelectedRow(), 0).toString());
        Tfnamakelas.setText(tm.getValueAt(tbmapel.getSelectedRow(), 1).toString());
        Tfkodekelas.setEnabled(false);
    }//GEN-LAST:event_tbmapelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tfkodekelas;
    private javax.swing.JTextField Tfkodekelas1;
    private javax.swing.JTextField Tfnamakelas;
    private javax.swing.JTextField Tfnamakelas1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jbox;
    private javax.swing.JPanel jbox1;
    private javax.swing.JTable tbmapel;
    // End of variables declaration//GEN-END:variables
}
