package UI.mahasiswa.mahasiswaPanel;

import DAO.StudentGradeDAO;
import Session.UserSession;
import Model.student;
import javax.swing.table.DefaultTableModel;
import java.util.List;

public class MhsGrade extends javax.swing.JPanel {

    private StudentGradeDAO gradeDAO = new StudentGradeDAO();
    private int studentId;

    public MhsGrade() {
        initComponents();
        initGradePanel();
    }

    private void initGradePanel() {
        student currentStudent = UserSession.getStudent();
        if (currentStudent == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Session mahasiswa tidak ditemukan!");
            return;
        }
        this.studentId = currentStudent.getStudentId();

        setupTableModel();
        loadSemesters();

        // Tampilkan semua semester pertama kali (atau semester terbaru)
        if (Semester.getItemCount() > 0) {
            Semester.setSelectedIndex(0);
            loadGradesForSelectedSemester();
        }
    }

    private void setupTableModel() {
        String[] columns = {"Mata Kuliah", "Semester", "Grade"};
        DefaultTableModel model = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable1.setModel(model);
    }

    private void loadSemesters() {
        Semester.removeAllItems();
        List<Integer> semesters = gradeDAO.getSemestersByStudent(studentId);
        for (Integer sem : semesters) {
            Semester.addItem("Semester " + sem);
        }
    }

    private void loadGradesForSelectedSemester() {
        int selectedIndex = Semester.getSelectedIndex();
        if (selectedIndex == -1) return;

        List<Integer> semesters = gradeDAO.getSemestersByStudent(studentId);
        int semesterId = semesters.get(selectedIndex);

        List<Object[]> data = gradeDAO.getGradesByStudentAndSemester(studentId, semesterId);

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); 

        for (Object[] row : data) {
            model.addRow(row);
        }
    }
    /**
     * Creates new form MhsGrade
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Semester = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mata Kuliah", "Semester", "Grade"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Grade History ");

        jLabel7.setText("Semester : ");

        Semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semester 1", "Semester 3", "Semester 2", "Semester 6" }));
        Semester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemesterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel7)
                        .addGap(28, 28, 28)
                        .addComponent(Semester, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel2)))
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemesterActionPerformed
       loadGradesForSelectedSemester(); 
    }//GEN-LAST:event_SemesterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Semester;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
